export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { MyProvider } from "@/Context/myContext"
import "./globals.css"

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en">
      <MyProvider>
        <body>{children}</body>
      </MyProvider>
    </html>
  )
}
